export const SPORTS = {
  football: {
    id: 'football',
    label: 'Football',
    icon: '\u26BD',
    dataFile: 'data/players.json',
    apiSportFilter: 'Soccer',
    seedOffset: 0,
    theme: { primary: '#1B5E20', primaryLight: '#2E7D32', primaryDark: '#0D3B13' },
    categories: {
      clubs: [
        { id: 'real_madrid', label: 'Real Madrid', value: 'Real Madrid', type: 'club', emoji: '\u{1F90D}' },
        { id: 'barcelona', label: 'Barcelona', value: 'Barcelona', type: 'club', emoji: '\u{1F535}\u{1F534}' },
        { id: 'man_united', label: 'Man United', value: 'Manchester United', type: 'club', emoji: '\u{1F534}' },
        { id: 'liverpool', label: 'Liverpool', value: 'Liverpool', type: 'club', emoji: '\u{1F534}' },
        { id: 'chelsea', label: 'Chelsea', value: 'Chelsea', type: 'club', emoji: '\u{1F535}' },
        { id: 'arsenal', label: 'Arsenal', value: 'Arsenal', type: 'club', emoji: '\u{1F534}\u26AA' },
        { id: 'man_city', label: 'Man City', value: 'Manchester City', type: 'club', emoji: '\u{1FA75}' },
        { id: 'bayern', label: 'Bayern Munich', value: 'Bayern Munich', type: 'club', emoji: '\u{1F534}\u26AA' },
        { id: 'juventus', label: 'Juventus', value: 'Juventus', type: 'club', emoji: '\u26AA\u26AB' },
        { id: 'ac_milan', label: 'AC Milan', value: 'AC Milan', type: 'club', emoji: '\u{1F534}\u26AB' },
        { id: 'inter', label: 'Inter Milan', value: 'Inter Milan', type: 'club', emoji: '\u{1F535}\u26AB' },
        { id: 'psg', label: 'PSG', value: 'PSG', type: 'club', emoji: '\u{1F535}\u{1F534}' },
        { id: 'atletico', label: 'Atletico Madrid', value: 'Atletico Madrid', type: 'club', emoji: '\u{1F534}\u26AA' },
        { id: 'dortmund', label: 'Dortmund', value: 'Borussia Dortmund', type: 'club', emoji: '\u{1F49B}' },
        { id: 'tottenham', label: 'Tottenham', value: 'Tottenham Hotspur', type: 'club', emoji: '\u26AA' },
        { id: 'napoli', label: 'Napoli', value: 'Napoli', type: 'club', emoji: '\u{1F535}' },
        { id: 'ajax', label: 'Ajax', value: 'Ajax', type: 'club', emoji: '\u{1F534}\u26AA' },
      ],
      countries: [
        { id: 'brazil', label: 'Brazil', value: 'Brazil', type: 'country', flag: 'br' },
        { id: 'argentina', label: 'Argentina', value: 'Argentina', type: 'country', flag: 'ar' },
        { id: 'france', label: 'France', value: 'France', type: 'country', flag: 'fr' },
        { id: 'germany', label: 'Germany', value: 'Germany', type: 'country', flag: 'de' },
        { id: 'spain', label: 'Spain', value: 'Spain', type: 'country', flag: 'es' },
        { id: 'england', label: 'England', value: 'England', type: 'country', flag: 'gb-eng' },
        { id: 'italy', label: 'Italy', value: 'Italy', type: 'country', flag: 'it' },
        { id: 'portugal', label: 'Portugal', value: 'Portugal', type: 'country', flag: 'pt' },
        { id: 'netherlands', label: 'Netherlands', value: 'Netherlands', type: 'country', flag: 'nl' },
      ],
      leagues: [
        { id: 'premier_league', label: 'Premier League', value: 'Premier League', type: 'league', flag: 'gb-eng' },
        { id: 'la_liga', label: 'La Liga', value: 'La Liga', type: 'league', flag: 'es' },
        { id: 'serie_a', label: 'Serie A', value: 'Serie A', type: 'league', flag: 'it' },
        { id: 'bundesliga', label: 'Bundesliga', value: 'Bundesliga', type: 'league', flag: 'de' },
        { id: 'ligue_1', label: 'Ligue 1', value: 'Ligue 1', type: 'league', flag: 'fr' },
      ],
      positions: [
        { id: 'goalkeeper', label: 'Goalkeeper', value: 'Goalkeeper', type: 'position', emoji: '\u{1F9E4}' },
        { id: 'defender', label: 'Defender', value: 'Defender', type: 'position', emoji: '\u{1F6E1}\uFE0F' },
        { id: 'midfielder', label: 'Midfielder', value: 'Midfielder', type: 'position', emoji: '\u{1F3AF}' },
        { id: 'forward', label: 'Forward', value: 'Forward', type: 'position', emoji: '\u26A1' },
      ],
      awards: [
        { id: 'ballon_dor', label: "Ballon d'Or", value: "Ballon d'Or", type: 'award', emoji: '\u{1F3C6}' },
        { id: 'world_cup', label: 'World Cup Winner', value: 'World Cup', type: 'award', emoji: '\u{1F3C6}' },
        { id: 'ucl', label: 'UCL Winner', value: 'Champions League', type: 'award', emoji: '\u{1F3C6}' },
      ],
    },
  },
  basketball: {
    id: 'basketball',
    label: 'Basketball',
    icon: '\u{1F3C0}',
    dataFile: 'data/nba_players.json',
    apiSportFilter: 'Basketball',
    seedOffset: 1,
    theme: { primary: '#C35817', primaryLight: '#D4722A', primaryDark: '#8B3A0F' },
    categories: {
      clubs: [
        { id: 'lakers', label: 'Lakers', value: 'Los Angeles Lakers', type: 'club', emoji: '\u{1F49C}\u{1F49B}' },
        { id: 'celtics', label: 'Celtics', value: 'Boston Celtics', type: 'club', emoji: '\u{1F49A}' },
        { id: 'bulls', label: 'Bulls', value: 'Chicago Bulls', type: 'club', emoji: '\u{1F534}' },
        { id: 'heat', label: 'Heat', value: 'Miami Heat', type: 'club', emoji: '\u{1F525}' },
        { id: 'warriors', label: 'Warriors', value: 'Golden State Warriors', type: 'club', emoji: '\u{1F49B}\u{1F535}' },
        { id: 'spurs', label: 'Spurs', value: 'San Antonio Spurs', type: 'club', emoji: '\u26AB\u26AA' },
        { id: 'nets', label: 'Nets', value: 'Brooklyn Nets', type: 'club', emoji: '\u26AB\u26AA' },
        { id: 'sixers', label: '76ers', value: 'Philadelphia 76ers', type: 'club', emoji: '\u{1F535}\u{1F534}' },
        { id: 'mavs', label: 'Mavericks', value: 'Dallas Mavericks', type: 'club', emoji: '\u{1F535}' },
        { id: 'rockets', label: 'Rockets', value: 'Houston Rockets', type: 'club', emoji: '\u{1F534}' },
        { id: 'clippers', label: 'Clippers', value: 'Los Angeles Clippers', type: 'club', emoji: '\u{1F535}\u{1F534}' },
        { id: 'nuggets', label: 'Nuggets', value: 'Denver Nuggets', type: 'club', emoji: '\u{1F49B}\u{1F535}' },
        { id: 'bucks', label: 'Bucks', value: 'Milwaukee Bucks', type: 'club', emoji: '\u{1F49A}' },
        { id: 'suns', label: 'Suns', value: 'Phoenix Suns', type: 'club', emoji: '\u{1F7E0}\u{1F49C}' },
        { id: 'raptors', label: 'Raptors', value: 'Toronto Raptors', type: 'club', emoji: '\u{1F534}' },
        { id: 'thunder', label: 'Thunder', value: 'Oklahoma City Thunder', type: 'club', emoji: '\u{1F535}\u{1F7E0}' },
        { id: 'knicks', label: 'Knicks', value: 'New York Knicks', type: 'club', emoji: '\u{1F535}\u{1F7E0}' },
        { id: 'cavs', label: 'Cavaliers', value: 'Cleveland Cavaliers', type: 'club', emoji: '\u{1F534}' },
        { id: 'pistons', label: 'Pistons', value: 'Detroit Pistons', type: 'club', emoji: '\u{1F535}\u{1F534}' },
        { id: 'pacers', label: 'Pacers', value: 'Indiana Pacers', type: 'club', emoji: '\u{1F49B}\u{1F535}' },
      ],
      countries: [
        { id: 'usa', label: 'USA', value: 'USA', type: 'country', flag: 'us' },
        { id: 'canada', label: 'Canada', value: 'Canada', type: 'country', flag: 'ca' },
        { id: 'france_bball', label: 'France', value: 'France', type: 'country', flag: 'fr' },
        { id: 'germany_bball', label: 'Germany', value: 'Germany', type: 'country', flag: 'de' },
        { id: 'spain_bball', label: 'Spain', value: 'Spain', type: 'country', flag: 'es' },
        { id: 'serbia', label: 'Serbia', value: 'Serbia', type: 'country', flag: 'rs' },
        { id: 'greece', label: 'Greece', value: 'Greece', type: 'country', flag: 'gr' },
        { id: 'australia_bball', label: 'Australia', value: 'Australia', type: 'country', flag: 'au' },
        { id: 'cameroon', label: 'Cameroon', value: 'Cameroon', type: 'country', flag: 'cm' },
        { id: 'slovenia', label: 'Slovenia', value: 'Slovenia', type: 'country', flag: 'si' },
      ],
      leagues: [
        { id: 'eastern', label: 'Eastern Conf.', value: 'Eastern Conference', type: 'league', emoji: '\u{1F1EA}' },
        { id: 'western', label: 'Western Conf.', value: 'Western Conference', type: 'league', emoji: '\u{1F1FC}' },
      ],
      positions: [
        { id: 'pg', label: 'Point Guard', value: 'Point Guard', type: 'position', emoji: '\u{1F3AF}' },
        { id: 'sg', label: 'Shooting Guard', value: 'Shooting Guard', type: 'position', emoji: '\u{1F3B0}' },
        { id: 'sf', label: 'Small Forward', value: 'Small Forward', type: 'position', emoji: '\u26A1' },
        { id: 'pf', label: 'Power Forward', value: 'Power Forward', type: 'position', emoji: '\u{1F4AA}' },
        { id: 'center', label: 'Center', value: 'Center', type: 'position', emoji: '\u{1F6E1}\uFE0F' },
      ],
      awards: [
        { id: 'mvp', label: 'MVP', value: 'MVP', type: 'award', emoji: '\u{1F3C6}' },
        { id: 'nba_champ', label: 'NBA Champion', value: 'NBA Champion', type: 'award', emoji: '\u{1F48D}' },
        { id: 'finals_mvp', label: 'Finals MVP', value: 'Finals MVP', type: 'award', emoji: '\u{1F3C6}' },
        { id: 'dpoy', label: 'DPOY', value: 'DPOY', type: 'award', emoji: '\u{1F6E1}\uFE0F' },
      ],
    },
  },
};
