export const SPORTS = {
  football: {
    id: 'football',
    label: 'Football',
    icon: '\u26BD',
    dataFile: 'data/players.json',
    apiSportFilter: 'Soccer',
    seedOffset: 0,
    theme: { primary: '#1B5E20', primaryLight: '#2E7D32', primaryDark: '#0D3B13' },
    categories: {
      clubs: [
        { id: 'real_madrid', label: 'Real Madrid', value: 'Real Madrid', type: 'club', emoji: '\u{1F90D}' },
        { id: 'barcelona', label: 'Barcelona', value: 'Barcelona', type: 'club', emoji: '\u{1F535}\u{1F534}' },
        { id: 'man_united', label: 'Man United', value: 'Manchester United', type: 'club', emoji: '\u{1F534}' },
        { id: 'liverpool', label: 'Liverpool', value: 'Liverpool', type: 'club', emoji: '\u{1F534}' },
        { id: 'chelsea', label: 'Chelsea', value: 'Chelsea', type: 'club', emoji: '\u{1F535}' },
        { id: 'arsenal', label: 'Arsenal', value: 'Arsenal', type: 'club', emoji: '\u{1F534}\u26AA' },
        { id: 'man_city', label: 'Man City', value: 'Manchester City', type: 'club', emoji: '\u{1FA75}' },
        { id: 'bayern', label: 'Bayern Munich', value: 'Bayern Munich', type: 'club', emoji: '\u{1F534}\u26AA' },
        { id: 'juventus', label: 'Juventus', value: 'Juventus', type: 'club', emoji: '\u26AA\u26AB' },
        { id: 'ac_milan', label: 'AC Milan', value: 'AC Milan', type: 'club', emoji: '\u{1F534}\u26AB' },
        { id: 'inter', label: 'Inter Milan', value: 'Inter Milan', type: 'club', emoji: '\u{1F535}\u26AB' },
        { id: 'psg', label: 'PSG', value: 'PSG', type: 'club', emoji: '\u{1F535}\u{1F534}' },
        { id: 'atletico', label: 'Atletico Madrid', value: 'Atletico Madrid', type: 'club', emoji: '\u{1F534}\u26AA' },
        { id: 'dortmund', label: 'Dortmund', value: 'Borussia Dortmund', type: 'club', emoji: '\u{1F49B}' },
        { id: 'tottenham', label: 'Tottenham', value: 'Tottenham Hotspur', type: 'club', emoji: '\u26AA' },
        { id: 'napoli', label: 'Napoli', value: 'Napoli', type: 'club', emoji: '\u{1F535}' },
        { id: 'ajax', label: 'Ajax', value: 'Ajax', type: 'club', emoji: '\u{1F534}\u26AA' },
      ],
      countries: [
        { id: 'brazil', label: 'Brazil', value: 'Brazil', type: 'country', flag: 'br' },
        { id: 'argentina', label: 'Argentina', value: 'Argentina', type: 'country', flag: 'ar' },
        { id: 'france', label: 'France', value: 'France', type: 'country', flag: 'fr' },
        { id: 'germany', label: 'Germany', value: 'Germany', type: 'country', flag: 'de' },
        { id: 'spain', label: 'Spain', value: 'Spain', type: 'country', flag: 'es' },
        { id: 'england', label: 'England', value: 'England', type: 'country', flag: 'gb-eng' },
        { id: 'italy', label: 'Italy', value: 'Italy', type: 'country', flag: 'it' },
        { id: 'portugal', label: 'Portugal', value: 'Portugal', type: 'country', flag: 'pt' },
        { id: 'netherlands', label: 'Netherlands', value: 'Netherlands', type: 'country', flag: 'nl' },
      ],
      leagues: [
        { id: 'premier_league', label: 'Premier League', value: 'Premier League', type: 'league', emoji: '\u26BD' },
        { id: 'la_liga', label: 'La Liga', value: 'La Liga', type: 'league', emoji: '\u26BD' },
        { id: 'serie_a', label: 'Serie A', value: 'Serie A', type: 'league', emoji: '\u26BD' },
        { id: 'bundesliga', label: 'Bundesliga', value: 'Bundesliga', type: 'league', emoji: '\u26BD' },
        { id: 'ligue_1', label: 'Ligue 1', value: 'Ligue 1', type: 'league', emoji: '\u26BD' },
      ],
      positions: [
        { id: 'goalkeeper', label: 'Goalkeeper', value: 'Goalkeeper', type: 'position', emoji: '\u{1F9E4}' },
        { id: 'defender', label: 'Defender', value: 'Defender', type: 'position', emoji: '\u{1F6E1}\uFE0F' },
        { id: 'midfielder', label: 'Midfielder', value: 'Midfielder', type: 'position', emoji: '\u{1F3AF}' },
        { id: 'forward', label: 'Forward', value: 'Forward', type: 'position', emoji: '\u26A1' },
      ],
      awards: [
        { id: 'ballon_dor', label: "Ballon d'Or", value: "Ballon d'Or", type: 'award', emoji: '\u{1F3C6}' },
        { id: 'world_cup', label: 'World Cup Winner', value: 'World Cup', type: 'award', emoji: '\u{1F3C6}' },
        { id: 'ucl', label: 'UCL Winner', value: 'Champions League', type: 'award', emoji: '\u{1F3C6}' },
      ],
    },
    rareAchievements: [
      { id: 'golden_boot', label: 'Golden Boot Winner', value: 'Golden Boot Winner', type: 'rare_achievement', emoji: '\u{1F45F}' },
      { id: 'golden_glove', label: 'Golden Glove Winner', value: 'Golden Glove Winner', type: 'rare_achievement', emoji: '\u{1F9E4}' },
      { id: 'hat_trick_goal', label: 'Scored a Hat-trick', value: 'Scored a Hat-trick', type: 'rare_achievement', emoji: '\u{1F3A9}' },
      { id: 'direct_free_kick', label: 'Direct Free Kick Goal', value: 'Scored a Direct Free Kick', type: 'rare_achievement', emoji: '\u{1F3AF}' },
      { id: 'bicycle_kick', label: 'Scored a Bicycle Kick', value: 'Scored a Bicycle Kick', type: 'rare_achievement', emoji: '\u{1F6B2}' },
      { id: 'red_card', label: 'Obtained a Red Card', value: 'Obtained a Red Card', type: 'rare_achievement', emoji: '\u{1F7E5}' },
    ],
  },
  basketball: {
    id: 'basketball',
    label: 'Basketball',
    icon: '\u{1F3C0}',
    dataFile: 'data/nba_players.json',
    apiSportFilter: 'Basketball',
    seedOffset: 1,
    theme: { primary: '#C35817', primaryLight: '#D4722A', primaryDark: '#8B3A0F' },
    categories: {
      clubs: [
        { id: 'lakers', label: 'Lakers', value: 'Los Angeles Lakers', type: 'club', emoji: '\u{1F49C}\u{1F49B}' },
        { id: 'celtics', label: 'Celtics', value: 'Boston Celtics', type: 'club', emoji: '\u{1F49A}' },
        { id: 'bulls', label: 'Bulls', value: 'Chicago Bulls', type: 'club', emoji: '\u{1F534}' },
        { id: 'heat', label: 'Heat', value: 'Miami Heat', type: 'club', emoji: '\u{1F525}' },
        { id: 'warriors', label: 'Warriors', value: 'Golden State Warriors', type: 'club', emoji: '\u{1F49B}\u{1F535}' },
        { id: 'spurs', label: 'Spurs', value: 'San Antonio Spurs', type: 'club', emoji: '\u26AB\u26AA' },
        { id: 'nets', label: 'Nets', value: 'Brooklyn Nets', type: 'club', emoji: '\u26AB\u26AA' },
        { id: 'sixers', label: '76ers', value: 'Philadelphia 76ers', type: 'club', emoji: '\u{1F535}\u{1F534}' },
        { id: 'mavs', label: 'Mavericks', value: 'Dallas Mavericks', type: 'club', emoji: '\u{1F535}' },
        { id: 'rockets', label: 'Rockets', value: 'Houston Rockets', type: 'club', emoji: '\u{1F534}' },
        { id: 'clippers', label: 'Clippers', value: 'Los Angeles Clippers', type: 'club', emoji: '\u{1F535}\u{1F534}' },
        { id: 'nuggets', label: 'Nuggets', value: 'Denver Nuggets', type: 'club', emoji: '\u{1F49B}\u{1F535}' },
        { id: 'bucks', label: 'Bucks', value: 'Milwaukee Bucks', type: 'club', emoji: '\u{1F49A}' },
        { id: 'suns', label: 'Suns', value: 'Phoenix Suns', type: 'club', emoji: '\u{1F7E0}\u{1F49C}' },
        { id: 'raptors', label: 'Raptors', value: 'Toronto Raptors', type: 'club', emoji: '\u{1F534}' },
        { id: 'thunder', label: 'Thunder', value: 'Oklahoma City Thunder', type: 'club', emoji: '\u{1F535}\u{1F7E0}' },
        { id: 'knicks', label: 'Knicks', value: 'New York Knicks', type: 'club', emoji: '\u{1F535}\u{1F7E0}' },
        { id: 'cavs', label: 'Cavaliers', value: 'Cleveland Cavaliers', type: 'club', emoji: '\u{1F534}' },
        { id: 'pistons', label: 'Pistons', value: 'Detroit Pistons', type: 'club', emoji: '\u{1F535}\u{1F534}' },
        { id: 'pacers', label: 'Pacers', value: 'Indiana Pacers', type: 'club', emoji: '\u{1F49B}\u{1F535}' },
      ],
      countries: [],
      leagues: [],
      positions: [
        { id: 'pg', label: 'Point Guard', value: 'Point Guard', type: 'position', emoji: '\u{1F3AF}' },
        { id: 'sg', label: 'Shooting Guard', value: 'Shooting Guard', type: 'position', emoji: '\u{1F3B0}' },
        { id: 'sf', label: 'Small Forward', value: 'Small Forward', type: 'position', emoji: '\u26A1' },
        { id: 'pf', label: 'Power Forward', value: 'Power Forward', type: 'position', emoji: '\u{1F4AA}' },
        { id: 'center', label: 'Center', value: 'Center', type: 'position', emoji: '\u{1F6E1}\uFE0F' },
      ],
      awards: [
        { id: 'mvp', label: 'MVP', value: 'MVP', type: 'award', emoji: '\u{1F3C6}' },
        { id: 'nba_champ', label: 'NBA Champion', value: 'NBA Champion', type: 'award', emoji: '\u{1F48D}' },
        { id: 'finals_mvp', label: 'Finals MVP', value: 'Finals MVP', type: 'award', emoji: '\u{1F3C6}' },
        { id: 'dpoy', label: 'DPOY', value: 'DPOY', type: 'award', emoji: '\u{1F6E1}\uFE0F' },
        { id: 'all_star', label: 'All-Star', value: 'All-Star', type: 'award', emoji: '\u2B50' },
      ],
    },
  },
  nfl: {
    id: 'nfl',
    label: 'NFL',
    icon: '\u{1F3C8}',
    dataFile: 'data/nfl_players.json',
    apiSportFilter: 'American Football',
    seedOffset: 2,
    theme: { primary: '#013369', primaryLight: '#1A4B8C', primaryDark: '#001A3E' },
    categories: {
      clubs: [
        { id: 'chiefs', label: 'Chiefs', value: 'Kansas City Chiefs', type: 'club', emoji: '\u{1F534}' },
        { id: 'patriots', label: 'Patriots', value: 'New England Patriots', type: 'club', emoji: '\u{1F535}\u{1F534}' },
        { id: '49ers', label: '49ers', value: 'San Francisco 49ers', type: 'club', emoji: '\u{1F534}\u{1F49B}' },
        { id: 'cowboys', label: 'Cowboys', value: 'Dallas Cowboys', type: 'club', emoji: '\u{1F535}\u26AA' },
        { id: 'packers', label: 'Packers', value: 'Green Bay Packers', type: 'club', emoji: '\u{1F49A}\u{1F49B}' },
        { id: 'steelers', label: 'Steelers', value: 'Pittsburgh Steelers', type: 'club', emoji: '\u{1F49B}\u26AB' },
        { id: 'ravens', label: 'Ravens', value: 'Baltimore Ravens', type: 'club', emoji: '\u{1F49C}\u26AB' },
        { id: 'eagles', label: 'Eagles', value: 'Philadelphia Eagles', type: 'club', emoji: '\u{1F49A}' },
        { id: 'broncos', label: 'Broncos', value: 'Denver Broncos', type: 'club', emoji: '\u{1F7E0}\u{1F535}' },
        { id: 'dolphins', label: 'Dolphins', value: 'Miami Dolphins', type: 'club', emoji: '\u{1F7E0}' },
        { id: 'seahawks', label: 'Seahawks', value: 'Seattle Seahawks', type: 'club', emoji: '\u{1F535}\u{1F49A}' },
        { id: 'bucs', label: 'Buccaneers', value: 'Tampa Bay Buccaneers', type: 'club', emoji: '\u{1F534}' },
        { id: 'bills', label: 'Bills', value: 'Buffalo Bills', type: 'club', emoji: '\u{1F535}\u{1F534}' },
        { id: 'rams', label: 'Rams', value: 'Los Angeles Rams', type: 'club', emoji: '\u{1F535}\u{1F49B}' },
        { id: 'giants', label: 'Giants', value: 'New York Giants', type: 'club', emoji: '\u{1F535}\u{1F534}' },
        { id: 'bears', label: 'Bears', value: 'Chicago Bears', type: 'club', emoji: '\u{1F535}\u{1F7E0}' },
        { id: 'lions', label: 'Lions', value: 'Detroit Lions', type: 'club', emoji: '\u{1F535}' },
        { id: 'chargers', label: 'Chargers', value: 'Los Angeles Chargers', type: 'club', emoji: '\u{1F535}\u{1F49B}' },
        { id: 'vikings', label: 'Vikings', value: 'Minnesota Vikings', type: 'club', emoji: '\u{1F49C}\u{1F49B}' },
        { id: 'jets', label: 'Jets', value: 'New York Jets', type: 'club', emoji: '\u{1F49A}' },
        { id: 'browns', label: 'Browns', value: 'Cleveland Browns', type: 'club', emoji: '\u{1F7E0}' },
        { id: 'falcons', label: 'Falcons', value: 'Atlanta Falcons', type: 'club', emoji: '\u{1F534}\u26AB' },
        { id: 'saints', label: 'Saints', value: 'New Orleans Saints', type: 'club', emoji: '\u{1F49B}\u26AB' },
        { id: 'texans', label: 'Texans', value: 'Houston Texans', type: 'club', emoji: '\u{1F534}\u{1F535}' },
        { id: 'colts', label: 'Colts', value: 'Indianapolis Colts', type: 'club', emoji: '\u{1F535}' },
        { id: 'raiders', label: 'Raiders', value: 'Las Vegas Raiders', type: 'club', emoji: '\u26AB\u26AA' },
        { id: 'panthers_nfl', label: 'Panthers', value: 'Carolina Panthers', type: 'club', emoji: '\u{1F535}' },
        { id: 'bengals', label: 'Bengals', value: 'Cincinnati Bengals', type: 'club', emoji: '\u{1F7E0}\u26AB' },
        { id: 'cardinals', label: 'Cardinals', value: 'Arizona Cardinals', type: 'club', emoji: '\u{1F534}' },
        { id: 'jaguars', label: 'Jaguars', value: 'Jacksonville Jaguars', type: 'club', emoji: '\u{1F7E0}' },
        { id: 'commanders', label: 'Commanders', value: 'Washington Commanders', type: 'club', emoji: '\u{1F534}\u{1F49B}' },
      ],
      countries: [],
      leagues: [],
      positions: [
        { id: 'qb', label: 'Quarterback', value: 'Quarterback', type: 'position', emoji: '\u{1F3AF}' },
        { id: 'rb', label: 'Running Back', value: 'Running Back', type: 'position', emoji: '\u{1F3C3}' },
        { id: 'wr', label: 'Wide Receiver', value: 'Wide Receiver', type: 'position', emoji: '\u{1F91A}' },
        { id: 'te', label: 'Tight End', value: 'Tight End', type: 'position', emoji: '\u{1F4AA}' },
        { id: 'de', label: 'Defensive End', value: 'Defensive End', type: 'position', emoji: '\u26A1' },
        { id: 'dt', label: 'Defensive Tackle', value: 'Defensive Tackle', type: 'position', emoji: '\u{1F6E1}\uFE0F' },
        { id: 'lb', label: 'Linebacker', value: 'Linebacker', type: 'position', emoji: '\u{1F4A5}' },
        { id: 'cb', label: 'Cornerback', value: 'Cornerback', type: 'position', emoji: '\u{1F6AB}' },
        { id: 'saf', label: 'Safety', value: 'Safety', type: 'position', emoji: '\u{1F441}\uFE0F' },
        { id: 'ol', label: 'O-Lineman', value: 'Offensive Lineman', type: 'position', emoji: '\u{1F9F1}' },
      ],
      awards: [
        { id: 'nfl_mvp', label: 'MVP', value: 'MVP', type: 'award', emoji: '\u{1F3C6}' },
        { id: 'sb_champ', label: 'Super Bowl Winner', value: 'Super Bowl Champion', type: 'award', emoji: '\u{1F48D}' },
        { id: 'sb_mvp', label: 'Super Bowl MVP', value: 'Super Bowl MVP', type: 'award', emoji: '\u{1F3C6}' },
        { id: 'nfl_dpoy', label: 'DPOY', value: 'DPOY', type: 'award', emoji: '\u{1F6E1}\uFE0F' },
        { id: 'pro_bowl', label: 'Pro Bowl', value: 'Pro Bowl', type: 'award', emoji: '\u2B50' },
      ],
    },
  },
  cricket: {
    id: 'cricket',
    label: 'Cricket',
    icon: '\u{1F3CF}',
    dataFile: 'data/cricket_players.json',
    apiSportFilter: 'Cricket',
    seedOffset: 3,
    theme: { primary: '#8B1A1A', primaryLight: '#A52A2A', primaryDark: '#5C1010' },
    categories: {
      clubs: [
        { id: 'csk', label: 'CSK', value: 'Chennai Super Kings', type: 'club', emoji: '\u{1F49B}' },
        { id: 'mi', label: 'Mumbai Indians', value: 'Mumbai Indians', type: 'club', emoji: '\u{1F535}' },
        { id: 'rcb', label: 'RCB', value: 'Royal Challengers Bangalore', type: 'club', emoji: '\u{1F534}' },
        { id: 'kkr', label: 'KKR', value: 'Kolkata Knight Riders', type: 'club', emoji: '\u{1F49C}' },
        { id: 'srh', label: 'SRH', value: 'Sunrisers Hyderabad', type: 'club', emoji: '\u{1F7E0}' },
        { id: 'dc', label: 'Delhi Capitals', value: 'Delhi Capitals', type: 'club', emoji: '\u{1F535}\u{1F534}' },
        { id: 'rr', label: 'Rajasthan Royals', value: 'Rajasthan Royals', type: 'club', emoji: '\u{1F49C}' },
        { id: 'pbks', label: 'PBKS', value: 'Punjab Kings', type: 'club', emoji: '\u{1F534}' },
        { id: 'gt', label: 'Gujarat Titans', value: 'Gujarat Titans', type: 'club', emoji: '\u{1F535}' },
        { id: 'lsg', label: 'Lucknow SG', value: 'Lucknow Super Giants', type: 'club', emoji: '\u{1FA75}' },
      ],
      countries: [
        { id: 'india', label: 'India', value: 'India', type: 'country', flag: 'in' },
        { id: 'australia', label: 'Australia', value: 'Australia', type: 'country', flag: 'au' },
        { id: 'england_cricket', label: 'England', value: 'England', type: 'country', flag: 'gb-eng' },
        { id: 'south_africa', label: 'South Africa', value: 'South Africa', type: 'country', flag: 'za' },
        { id: 'new_zealand', label: 'New Zealand', value: 'New Zealand', type: 'country', flag: 'nz' },
        { id: 'west_indies', label: 'West Indies', value: 'West Indies', type: 'country', flagUrl: 'assets/flags/west-indies.png' },
        { id: 'pakistan', label: 'Pakistan', value: 'Pakistan', type: 'country', flag: 'pk' },
        { id: 'sri_lanka', label: 'Sri Lanka', value: 'Sri Lanka', type: 'country', flag: 'lk' },
        { id: 'bangladesh', label: 'Bangladesh', value: 'Bangladesh', type: 'country', flag: 'bd' },
        { id: 'afghanistan', label: 'Afghanistan', value: 'Afghanistan', type: 'country', flag: 'af' },
      ],
      leagues: [],
      positions: [
        { id: 'batsman', label: 'Batsman', value: 'Batsman', type: 'position', emoji: '\u{1F3CF}' },
        { id: 'bowler', label: 'Bowler', value: 'Bowler', type: 'position', emoji: '\u{1F94E}' },
        { id: 'all_rounder', label: 'All-Rounder', value: 'All-Rounder', type: 'position', emoji: '\u2B50' },
        { id: 'wicketkeeper', label: 'Wicket-Keeper', value: 'Wicket-Keeper', type: 'position', emoji: '\u{1F9E4}' },
      ],
      awards: [
        { id: 'icc_wc', label: 'World Cup Winner', value: 'World Cup Winner', type: 'award', emoji: '\u{1F3C6}' },
        { id: 'ipl_winner', label: 'IPL Winner', value: 'IPL Winner', type: 'award', emoji: '\u{1F48D}' },
        { id: 'icc_poty', label: 'ICC Player of the Year', value: 'ICC Player of the Year', type: 'award', emoji: '\u{1F3C6}' },
      ],
    },
    rareAchievements: [
      { id: 'hat_trick_bowl', label: 'Bowled a Hat-trick', value: 'Bowled a Hat-trick', type: 'rare_achievement', emoji: '\u{1F3A9}' },
      { id: 'most_wickets_ipl', label: 'Most Wickets in IPL Season', value: 'Most Wickets in IPL Season', type: 'rare_achievement', emoji: '\u{1F3CF}' },
      { id: 'most_runs_ipl', label: 'Most Runs in IPL Season', value: 'Most Runs in IPL Season', type: 'rare_achievement', emoji: '\u{1F3CF}' },
      { id: 'century_under_50', label: '100 under 50 Balls', value: 'Scored 100 under 50 Balls', type: 'rare_achievement', emoji: '\u26A1' },
      { id: 'scored_150_plus', label: '150+ in a Single Game', value: 'Scored 150+ in a Single Game', type: 'rare_achievement', emoji: '\u{1F525}' },
      { id: 'five_wickets', label: '5+ Wickets in a Match', value: '5+ Wickets in a Single Match', type: 'rare_achievement', emoji: '\u{1F4A5}' },
    ],
  },
};
